Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyCompany.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

Models/ViewComponents/SidebarViewComponent.cs
using System.Configuration;
using System.Drawing;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using System.Net;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Xml.Linq;

namespace MyCompany.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
			
			return Task.FromResult((IViewComponentResult)View("Default", dataManager.NewsItems.GetLastServiceItems(1)));

        }


    }
}

Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.NewsItems.GetServiceItems());
        }

		public IActionResult SetLanguage(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}


}

Areas/Admin/Controllers/NewsItemsController.cs
using System;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public NewsItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetServiceItemById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(NewsItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.NewsItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.NewsItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }

		public IActionResult SetLanguage(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}
}

Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Models;

namespace MyCompany.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
			
			if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
			await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

		public IActionResult SetLanguage(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
			
			return View(dataManager.NewsItems.GetLastServiceItems(3));
        }

        public IActionResult Contacts()
        {
			
			return View();
        }

		public IActionResult SetLanguage(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}
}

Controllers/NewsController.cs
using System;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
    public class NewsController : Controller
    {
		
        private readonly DataManager dataManager;

        public NewsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
			
			if (id != default)
            {
                return View("Show", dataManager.NewsItems.GetServiceItemById(id));
            }

            
            return View(dataManager.NewsItems.GetServiceItems());
        }

		public IActionResult SetLanguage(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}
}

Areas/Admin/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model IQueryable<NewsItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>@Localizer["News"]</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="">@Localizer["AddNews"]</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (NewsItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="@entity.Id">@Localizer["EditNews"]</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="NewsItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">@Localizer["DelNews"]</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <p> </p>
    <p> </p>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="@Localizer["Exit"]" />
        </form>
    </div>
</div>

Areas/Admin/Views/NewsItems/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model NewsItem
@{
    string strTitle = "Редактировать запись";  
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label>@Localizer["NewsTittle"]</label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label>@Localizer["NewsSubTittle"]</label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label>@Localizer["NewsText"]</label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label>@Localizer["NewsImage"]</label>
                <input type="file" name="TitleImageFile" id="TitleImageFile" />
                <div>
                    <img class="img-block" style="max-width:300px" src="~/images/@Model.TitleImagePath" resource="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            
           
            <input type="submit" value='@Localizer["NewsButton"].Value' />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Views/Home/Contacts.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@Html.Raw(Localizer["Text"].Value)
</div>

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model IQueryable<NewsItem>
@{
	//ViewBag.Title = textField.MetaTitle;
}



 
    
<section class="box article-list">
	<h2 class="icon fa-file-alt">@Localizer["NewsTittle"]</h2>

	@if (Model.Any())
	{

		@foreach (NewsItem entity in Model)
		{


			<!-- Excerpt -->
			<article class="box excerpt">
				<a class="image left" asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
					<img src="~/images/@entity.TitleImagePath" alt="" />
				</a>
				<div>
					<header>
						<span class="date">@entity.DateAdded.ToShortDateString()</span>
						<h3><a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id"> <p>@entity.Subtitle</p></a></h3>
					</header>
					<p>
						@entity.Title
					</p>
				</div>
			</article>
		}
		<footer style="text-align:center">
			<a asp-area="" asp-controller="News" asp-action="Index" class="button alt icon solid fa-file-alt" style="background-color:red">@Localizer["ButtonText"]</a>
		</footer>

	}
	else
	{
		<h1>@Localizer["ErrorNews"]</h1>
	}
</section>

Views/News/Index.cshtml
@model IQueryable<NewsItem>
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
	//ViewBag.Title = textField.MetaTitle;
	
}




<section class="box article-list">
	<h2 class="icon fa-file-alt">@Localizer["NewsTittle"]</h2>
	@if (Model.Any())
	{

		@foreach (NewsItem entity in Model)
		{


			<!-- Excerpt -->
			<article class="box excerpt">
				<a class="image left" asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
					<img src="~/images/@entity.TitleImagePath" alt="" />
				</a>
				<div>
					<header>
						<span class="date">@entity.DateAdded.ToShortDateString()</span>
						<h3><a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id"> <p>@entity.Subtitle</p></a></h3>
					</header>
					<p>
						@entity.Title
					</p>
				</div>
			</article>
		}
	}
	else
	{
		<h1>Новостей нет. Ожидайте!</h1>
	}
</section>



       
               
                    
            
    

Views/News/Show.cshtml
@model NewsItem
@{
    //ViewBag.Title = Model.MetaTitle;
    //ViewBag.Description = Model.MetaDiscription;
}


<!-- Content -->

<article>
	@Model.DateAdded	
	<header class="major">
		<h2> @Model.Title</h2>
		<p>@Model.Subtitle</p>
	</header>

	<span class="image featured"> <img class="img-block" src="~/images/@Model.TitleImagePath" /></span>

	<p>
		@Html.Raw(Model.Text)
	</p>


</article>

Views/Shared/Components/Sidebar/Default.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
@model IQueryable<NewsItem>

@{
	//ViewBag.Title = textField.MetaTitle;

}

<article>
   @if (@Model.Any())
	{

		@foreach (NewsItem entity in @Model)
		{
				
						<a href="#" class="image featured"><img src="~/images/@entity.TitleImagePath" alt=""></a>
						<header>
							<h3><a href="#">@entity.Title</a></h3>
							<p>@entity.Subtitle</p>
						</header>

			<div style=" white-space: nowrap; overflow: hidden;text-overflow: ellipsis;">

				@Html.Raw(@entity.Text)
						</div>

			<a class="button alt icon solid fa-file-alt" asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id"></a>
		}
	}
	<footer>

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true" />

Views/Shared/FooterPartial.cshtml
<!-- Footer Wrapper -->
<div id="footer-wrapper">
	<footer id="footer" class="container">
		<div class="row">
			<div class="col-3 col-6-medium col-12-small">

				<!-- Links -->
				<section>
					<h2>Filler Links</h2>
					<ul class="divided">
						<li><a href="#">Quam turpis feugiat dolor</a></li>
						<li><a href="#">Amet ornare in hendrerit </a></li>
						<li><a href="#">Semper mod quisturpis nisi</a></li>
						<li><a href="#">Consequat etiam phasellus</a></li>
						<li><a href="#">Amet turpis, feugiat et</a></li>
						<li><a href="#">Ornare hendrerit lectus</a></li>
						<li><a href="#">Semper mod quis et dolore</a></li>
						<li><a href="#">Amet ornare in hendrerit</a></li>
						<li><a href="#">Consequat lorem phasellus</a></li>
						<li><a href="#">Amet turpis, feugiat amet</a></li>
						<li><a href="#">Semper mod quisturpis</a></li>
					</ul>
				</section>

			</div>
			<div class="col-3 col-6-medium col-12-small">

				<!-- Links -->
				<section>
					<h2>More Filler</h2>
					<ul class="divided">
						<li><a href="#">Quam turpis feugiat dolor</a></li>
						<li><a href="#">Amet ornare in in lectus</a></li>
						<li><a href="#">Semper mod sed tempus nisi</a></li>
						<li><a href="#">Consequat etiam phasellus</a></li>
					</ul>
				</section>

				<!-- Links -->
				<section>
					<h2>Even More Filler</h2>
					<ul class="divided">
						<li><a href="#">Quam turpis feugiat dolor</a></li>
						<li><a href="#">Amet ornare hendrerit lectus</a></li>
						<li><a href="#">Semper quisturpis nisi</a></li>
						<li><a href="#">Consequat lorem phasellus</a></li>
					</ul>
				</section>

			</div>
			<div class="col-6 col-12-medium imp-medium">

				<!-- About -->
				<section>
					<h2><strong>ZeroFour</strong> by HTML5 UP</h2>
					<p>
						Hi! This is <strong>ZeroFour</strong>, a free, fully responsive HTML5 site
						template by <a href="http://twitter.com/ajlkn">AJ</a> for <a href="http://html5up.net/">HTML5 UP</a>.
						It's <a href="http://html5up.net/license/">Creative Commons Attribution</a>
						licensed so use it for any personal or commercial project (just credit us
						for the design!).
					</p>
					<a href="#" class="button alt icon solid fa-arrow-circle-right">Learn More</a>
				</section>

				<!-- Contact -->
				<section>
					<h2>Get in touch</h2>
					<div>
						<div class="row">
							<div class="col-6 col-12-small">
								<dl class="contact">
									<dt>Twitter</dt>
									<dd><a href="#">untitled-corp</a></dd>
									<dt>Facebook</dt>
									<dd><a href="#">facebook.com/untitled</a></dd>
									<dt>WWW</dt>
									<dd><a href="#">untitled.tld</a></dd>
									<dt>Email</dt>
									<dd><a href="#">user@untitled.tld</a></dd>
								</dl>
							</div>
							<div class="col-6 col-12-small">
								<dl class="contact">
									<dt>Address</dt>
									<dd>
										1234 Fictional Rd<br />
										Nashville, TN 00000-0000<br />
										USA
									</dd>
									<dt>Phone</dt>
									<dd>(000) 000-0000</dd>
								</dl>
							</div>
						</div>
					</div>
				</section>

			</div>
			<div class="col-12">
				<div id="copyright">
					<ul class="menu">
						<li>&copy; Untitled. All rights reserved</li>
						<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
</div>

Views/Shared/HeaderPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
@{
	int numToCheck = 1;
}
<div id="header-wrapper">
	<div class="container">

		<!-- Header -->
		<header id="header">
			<div class="inner">
				
				<!-- Logo -->
				<h1><a asp-area="" asp-controller="Home" asp-action="Index">@Config.CompanyName</a></h1>

				<!-- Nav -->
				<nav id="nav">
					<ul>
						@while(!Localizer["Menu"+numToCheck.ToString()+"Controller"].IsResourceNotFound)
						{
							<li><a asp-area="" asp-controller='@Localizer["Menu"+numToCheck.ToString()+"Controller"].Value' asp-action='@Localizer["Menu"+numToCheck.ToString()+"Action"].Value'>@Localizer["Menu"+numToCheck.ToString()+"Text"]</a></li>
							numToCheck++;
						}
						
						
					</ul>
				</nav>

			</div>
		</header>

		

	</div>
</div>

Views/Shared/MetatagsPartial.cshtml
@using MyCompany.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Views/Shared/SidebarPartial.cshtml
@using MyCompany.Models.ViewComponents;
<div class="col-4 col-12-medium">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!DOCTYPE HTML>

<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	@await Html.PartialAsync("MetatagsPartial")
	@await Html.PartialAsync("CssPartial")
</head>
<body class="homepage is-preload">
	<div id="page-wrapper">

		<!-- Header -->
		@await Html.PartialAsync("HeaderPartial")

		<!-- Main Wrapper -->
		<div id="main-wrapper">
			
			<div class="wrapper style3">
				
				<div class="inner">
					
					<div class="container">
						
						<div class="row">

							<div class="col-8 col-12-medium">
								<div style="position: absolute; left:0px; top:0px;">
									@await Html.PartialAsync("_SelectLanguagePartial")
								</div>
								@RenderBody()

								
								
							</div>
							<div class="col-4 col-12-medium">

								<!-- Spotlight -->
								<section class="box spotlight">
									<h2 class="icon fa-file-alt">@Localizer["NewsTittle"].Value</h2>
								@await Html.PartialAsync("SidebarPartial")
									
									</footer>
									</article>
								</section>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		@await Html.PartialAsync("FooterPartial")

	</div>

	@await Html.PartialAsync("ScriptsPartial")
	

</body>
</html>

Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    <select name="culture" onchange="this.form.submit();"
                      asp-for="@requestCulture.RequestCulture.UICulture.Name"
                      asp-items="cultureItems"></select>
</form>